version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
  build:
    commands:
      - echo "Zipping lambda code"
      - zip -r build_output.zip lambda/
artifacts:
  files:
    - build_output.zip
